import type { Metadata } from "next"
import { Inter as FontSans } from "next/font/google"
import { JetBrains_Mono as FontMono } from "next/font/google"

import { cn } from "@/lib/utils"
import { ThemeProvider } from "@/components/theme-provider"
import { TimeProvider } from "@/providers/TimeProvider"
import { WeatherProvider } from "@/providers/WeatherProvider"

import "./globals.css"
import { getCurrentHourTheme } from "@/lib/theme-utils"
import DynamicBackground from "@/components/background/DynamicBackground"
import { ShadcnThemeController } from "@/components/ui/shadcn-theme-controller";
import WeatherWidget from "@/components/weather/WeatherWidget"

// Define fonts
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-geist-sans",
})

const fontMono = FontMono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <style>{`
          body::before {
            content: "";
            position: fixed;
            inset: 0;
            background: linear-gradient(to bottom, #0A1128, #1e3c72);
            z-index: -1;
            transition: opacity 0.3s ease;
          }
          .mounted body::before {
            opacity: 0;
          }
        `}</style>
        <script dangerouslySetInnerHTML={{
          __html: `
            setTimeout(function() {
              document.documentElement.classList.add('mounted');
            }, 300);
          `
        }} />
      </head>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
          fontMono.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme={getCurrentHourTheme()}
          enableSystem={false}
          disableTransitionOnChange
        >
          <TimeProvider>
            <WeatherProvider>
              {/* Background layer */}
              <ShadcnThemeController />
              <DynamicBackground />
              
              {/* Content layer */}
              <div className="relative z-10">
                {children}
              </div>
              
              {/* UI overlay layer */}
              <WeatherWidget />
            </WeatherProvider>
          </TimeProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
